/** Демонстрационная витрина. Цены и характеристики — ориентир, не оферта и не расчёт брокера. */
window.MOST = {
  brand: "МОСТ",
  asOf: "30 сентября 2026",
  rate: 12.5,
  moscowExtraRub: 180000,
  cars: [
    {
      id: "camry-25h",
      brand: "Toyota",
      model: "Camry",
      trim: "2.5 Hybrid",
      year: 2024,
      condition: "used",
      mileageKm: 27300,
      body: "sedan",
      fuel: "Гибрид",
      engine: "2.5 гибрид · 218 л.с.",
      drive: "Передний",
      gear: "Автомат",
      rangeNote: "",
      color: "Белый",
      city: "Гуанчжоу",
      priceCny: 128600,
      logisticsRub: 180000,
      feesRub: 390000,
      featured: true,
      points: ["С пробегом, один кузов", "Гибрид", "Легко проверить по видео"],
    },
    {
      id: "byd-song-plus",
      brand: "BYD",
      model: "Song Plus",
      trim: "DM-i Champion",
      year: 2026,
      condition: "new",
      mileageKm: 0,
      body: "crossover",
      fuel: "Гибрид",
      engine: "1.5 DM-i · 197 л.с.",
      drive: "Передний",
      gear: "Автомат DHT",
      rangeNote: "около 150 км на электротяге",
      color: "Серый",
      city: "Сиань",
      priceCny: 139800,
      logisticsRub: 220000,
      feesRub: 480000,
      featured: true,
      points: ["Без пробега", "Запас хода на батарее", "Кроссовер для города"],
    },
    {
      id: "uni-k",
      brand: "Changan",
      model: "UNI-K",
      trim: "2.0T",
      year: 2025,
      condition: "new",
      mileageKm: 0,
      body: "crossover",
      fuel: "Бензин",
      engine: "2.0 турбо · 233 л.с.",
      drive: "Полный",
      gear: "Автомат",
      rangeNote: "",
      color: "Синий",
      city: "Чунцин",
      priceCny: 145800,
      logisticsRub: 220000,
      feesRub: 500000,
      featured: false,
      points: ["Полный привод", "Без пробега", "Просторный салон"],
    },
    {
      id: "tiggo-8",
      brand: "Chery",
      model: "Tiggo 8 Pro Max",
      trim: "2.0T",
      year: 2026,
      condition: "new",
      mileageKm: 0,
      body: "crossover",
      fuel: "Бензин",
      engine: "2.0 турбо · 254 л.с.",
      drive: "Полный",
      gear: "Автомат",
      rangeNote: "",
      color: "Чёрный",
      city: "Уху",
      priceCny: 154900,
      logisticsRub: 230000,
      feesRub: 540000,
      featured: false,
      points: ["7 мест", "Полный привод", "Без пробега"],
    },
    {
      id: "hongqi-h5",
      brand: "Hongqi",
      model: "H5",
      trim: "2.0T Deluxe",
      year: 2026,
      condition: "new",
      mileageKm: 0,
      body: "sedan",
      fuel: "Бензин",
      engine: "2.0 турбо · 224 л.с.",
      drive: "Передний",
      gear: "Автомат",
      rangeNote: "",
      color: "Красный",
      city: "Чанчунь",
      priceCny: 159800,
      logisticsRub: 190000,
      feesRub: 560000,
      featured: false,
      points: ["Бизнес-седан", "Без пробега", "Спокойная трасса"],
    },
    {
      id: "tank-300",
      brand: "Tank",
      model: "300",
      trim: "Conqueror",
      year: 2024,
      condition: "used",
      mileageKm: 18600,
      body: "suv",
      fuel: "Бензин",
      engine: "2.0 турбо · 220 л.с.",
      drive: "Полный",
      gear: "Автомат",
      rangeNote: "",
      color: "Зелёный",
      city: "Тяньцзинь",
      priceCny: 168000,
      logisticsRub: 260000,
      feesRub: 720000,
      featured: false,
      points: ["Рама", "Полный привод", "Небольшой пробег"],
    },
    {
      id: "monjaro",
      brand: "Geely",
      model: "Monjaro",
      trim: "Flagship",
      year: 2025,
      condition: "new",
      mileageKm: 0,
      body: "crossover",
      fuel: "Бензин",
      engine: "2.0 турбо · 238 л.с.",
      drive: "Полный",
      gear: "Автомат",
      rangeNote: "",
      color: "Белый",
      city: "Ханчжоу",
      priceCny: 178800,
      logisticsRub: 230000,
      feesRub: 610000,
      featured: false,
      points: ["Полный привод", "Без пробега", "Высокая комплектация"],
    },
    {
      id: "exeed-rx",
      brand: "Exeed",
      model: "RX",
      trim: "Flagship",
      year: 2025,
      condition: "new",
      mileageKm: 0,
      body: "crossover",
      fuel: "Бензин",
      engine: "2.0 турбо · 249 л.с.",
      drive: "Полный",
      gear: "Автомат",
      rangeNote: "",
      color: "Серый",
      city: "Уху",
      priceCny: 192800,
      logisticsRub: 230000,
      feesRub: 640000,
      featured: false,
      points: ["Полный привод", "Без пробега", "Тише Tiggo по салону"],
    },
    {
      id: "zeekr-001",
      brand: "Zeekr",
      model: "001",
      trim: "WE",
      year: 2024,
      condition: "used",
      mileageKm: 12400,
      body: "liftback",
      fuel: "Электро",
      engine: "Два мотора · 544 л.с.",
      drive: "Полный",
      gear: "Редуктор",
      rangeNote: "до 580 км по паспорту",
      color: "Серый",
      city: "Нинбо",
      priceCny: 219000,
      logisticsRub: 200000,
      feesRub: 980000,
      featured: false,
      points: ["Полный привод", "Лифтбек", "Небольшой пробег"],
    },
    {
      id: "byd-seal",
      brand: "BYD",
      model: "Seal",
      trim: "Excellence AWD",
      year: 2026,
      condition: "new",
      mileageKm: 0,
      body: "sedan",
      fuel: "Электро",
      engine: "Два мотора · 530 л.с.",
      drive: "Полный",
      gear: "Редуктор",
      rangeNote: "до 650 км по паспорту",
      color: "Серый",
      city: "Шэньчжэнь",
      priceCny: 239800,
      logisticsRub: 190000,
      feesRub: 920000,
      featured: true,
      points: ["Полный привод", "Без пробега", "Запас хода по паспорту"],
    },
    {
      id: "li-l6",
      brand: "Li Auto",
      model: "L6",
      trim: "Max",
      year: 2026,
      condition: "new",
      mileageKm: 0,
      body: "suv",
      fuel: "Гибрид",
      engine: "EREV · 408 л.с.",
      drive: "Полный",
      gear: "Редуктор",
      rangeNote: "около 212 км на электротяге, далее бак",
      color: "Белый",
      city: "Чанчжоу",
      priceCny: 249800,
      logisticsRub: 250000,
      feesRub: 1100000,
      featured: false,
      points: ["Семейный SUV", "Полный привод", "Бак после батареи"],
    },
    {
      id: "voyah-dreamer",
      brand: "Voyah",
      model: "Dreamer",
      trim: "PHEV",
      year: 2025,
      condition: "used",
      mileageKm: 9800,
      body: "minivan",
      fuel: "Гибрид",
      engine: "PHEV · 422 л.с.",
      drive: "Полный",
      gear: "Автомат",
      rangeNote: "около 150 км на электротяге",
      color: "Чёрный",
      city: "Ухань",
      priceCny: 289000,
      logisticsRub: 280000,
      feesRub: 860000,
      featured: false,
      points: ["Минивэн", "Полный привод", "Малый пробег"],
    },
  ],
};
